[workspace]
members = [
    "async",
    "collector",
    "condensator",
    "fib",
    "meta",
    "minimal",
    "panicker",
    "ping",
    "sum",
    "vec",
]

[profile.release]
lto = true
opt-level = 's'
