[package]
name = "galloc"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
# add "checks" feature to enable hard checks in allocator
# dlmalloc = { git = "https://github.com/gear-tech/dlmalloc-rust.git", rev = "703192a04d55a75899a69ca8c9f70810de421797" }
dlmalloc = { git = "https://github.com/gear-tech/dlmalloc-rust.git", rev = "e76ae98", default-features = false, features = ["global"] }

[features]
debug = ["dlmalloc/debug"]

