name: CD

on:
  push:
    branches: [master,cd-fix]

env:
  CARGO_TERM_COLOR: always
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Info
        run: |
            ls -l .
            ls -l ../..
            pwd
