name: Del-DB-on-node

on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  Deploy:
    runs-on: ubuntu-latest
    needs: Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Info
        run: |
            ls -l .
            ls -l ../..
            pwd
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          directory: ./ansible/
          playbook: mainj3.yaml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [gearNodes:children]
            bootnode
            nodes
            [bootnode]
            ${{secrets.GEAR_NODE}} 
            [nodes]
            ${{secrets.GEAR_NODE_2}} bootnode=${{secrets.GEAR_NODE}} bootnodeId=${{secrets.BOOTNODEID}} validator=yes
            ${{secrets.GEAR_NODE_3}} bootnode=${{secrets.GEAR_NODE}} bootnodeId=${{secrets.BOOTNODEID}} rpc=yes
            ${{secrets.GEAR_NODE_4}} bootnode=${{secrets.GEAR_NODE}} bootnodeId=${{secrets.BOOTNODEID}} validator=yes 
