name: Upgrade-runtime

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
jobs:
  upgrade-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: "Install: Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install polkadot-js-api
        run: npm install -g @polkadot/api-cli

      - name: Send reset extrinsic
        run: polkadot-js-api --ws wss://rpc-node.gear-tech.io:443 --sudo --seed "${{ secrets.ROOT_SEED }}" tx.gear.reset
